# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

overwrite_arr <- function(dst, dst_indices, src, src_indices) {
    .Call('_jheem_core_overwrite_arr', PACKAGE = 'jheem.core', dst, dst_indices, src, src_indices)
}

add_to_arr <- function(dst, dst_indices, src, src_indices) {
    .Call('_jheem_core_add_to_arr', PACKAGE = 'jheem.core', dst, dst_indices, src, src_indices)
}

overwrite_arr_with_scalar <- function(dst, overwrite_with) {
    .Call('_jheem_core_overwrite_arr_with_scalar', PACKAGE = 'jheem.core', dst, overwrite_with)
}

add_scalar_to_arr <- function(dst, to_add) {
    .Call('_jheem_core_add_scalar_to_arr', PACKAGE = 'jheem.core', dst, to_add)
}

do_array_overwrite <- function(dst_array, src_array, dimension_values) {
    .Call('_jheem_core_do_array_overwrite', PACKAGE = 'jheem.core', dst_array, src_array, dimension_values)
}

do_expand_array <- function(dst_array, src_array) {
    .Call('_jheem_core_do_expand_array', PACKAGE = 'jheem.core', dst_array, src_array)
}

do_get_expand_indices <- function(dst_array, src_dim_names, index_from) {
    .Call('_jheem_core_do_get_expand_indices', PACKAGE = 'jheem.core', dst_array, src_dim_names, index_from)
}

do_access_overwrite <- function(dst, src, dst_indices, src_indices) {
    .Call('_jheem_core_do_access_overwrite', PACKAGE = 'jheem.core', dst, src, dst_indices, src_indices)
}

do_access_add <- function(dst, src, dst_indices, src_indices) {
    .Call('_jheem_core_do_access_add', PACKAGE = 'jheem.core', dst, src, dst_indices, src_indices)
}

do_access_subtract <- function(dst, src, dst_indices, src_indices) {
    .Call('_jheem_core_do_access_subtract', PACKAGE = 'jheem.core', dst, src, dst_indices, src_indices)
}

do_access_multiply <- function(dst, src, dst_indices, src_indices) {
    .Call('_jheem_core_do_access_multiply', PACKAGE = 'jheem.core', dst, src, dst_indices, src_indices)
}

do_access_divide <- function(dst, src, dst_indices, src_indices) {
    .Call('_jheem_core_do_access_divide', PACKAGE = 'jheem.core', dst, src, dst_indices, src_indices)
}

apply_ontology_mapping <- function(src, dst, from_values, to_values, na_rm) {
    .Call('_jheem_core_apply_ontology_mapping', PACKAGE = 'jheem.core', src, dst, from_values, to_values, na_rm)
}

get_ontology_mapping_matrix <- function(src_dim_names, dst_dim_names, dst, from_values, to_values) {
    .Call('_jheem_core_get_ontology_mapping_matrix', PACKAGE = 'jheem.core', src_dim_names, dst_dim_names, dst, from_values, to_values)
}

get_ontology_mapping_indices <- function(src_dim_names, dst_dim_names, from_values, to_values) {
    .Call('_jheem_core_get_ontology_mapping_indices', PACKAGE = 'jheem.core', src_dim_names, dst_dim_names, from_values, to_values)
}

do_get_reverse_indices_from_forward <- function(forward_indices, n_from) {
    .Call('_jheem_core_do_get_reverse_indices_from_forward', PACKAGE = 'jheem.core', forward_indices, n_from)
}

