// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// overwrite_arr
NumericVector overwrite_arr(NumericVector dst, IntegerVector dst_indices, NumericVector src, IntegerVector src_indices);
RcppExport SEXP _jheem_core_overwrite_arr(SEXP dstSEXP, SEXP dst_indicesSEXP, SEXP srcSEXP, SEXP src_indicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type dst(dstSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dst_indices(dst_indicesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type src(srcSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type src_indices(src_indicesSEXP);
    rcpp_result_gen = Rcpp::wrap(overwrite_arr(dst, dst_indices, src, src_indices));
    return rcpp_result_gen;
END_RCPP
}
// add_to_arr
NumericVector add_to_arr(NumericVector dst, IntegerVector dst_indices, NumericVector src, IntegerVector src_indices);
RcppExport SEXP _jheem_core_add_to_arr(SEXP dstSEXP, SEXP dst_indicesSEXP, SEXP srcSEXP, SEXP src_indicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type dst(dstSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dst_indices(dst_indicesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type src(srcSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type src_indices(src_indicesSEXP);
    rcpp_result_gen = Rcpp::wrap(add_to_arr(dst, dst_indices, src, src_indices));
    return rcpp_result_gen;
END_RCPP
}
// overwrite_arr_with_scalar
NumericVector overwrite_arr_with_scalar(NumericVector dst, NumericVector overwrite_with);
RcppExport SEXP _jheem_core_overwrite_arr_with_scalar(SEXP dstSEXP, SEXP overwrite_withSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type dst(dstSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type overwrite_with(overwrite_withSEXP);
    rcpp_result_gen = Rcpp::wrap(overwrite_arr_with_scalar(dst, overwrite_with));
    return rcpp_result_gen;
END_RCPP
}
// add_scalar_to_arr
NumericVector add_scalar_to_arr(NumericVector dst, NumericVector to_add);
RcppExport SEXP _jheem_core_add_scalar_to_arr(SEXP dstSEXP, SEXP to_addSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type dst(dstSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type to_add(to_addSEXP);
    rcpp_result_gen = Rcpp::wrap(add_scalar_to_arr(dst, to_add));
    return rcpp_result_gen;
END_RCPP
}
// do_array_overwrite
RObject do_array_overwrite(NumericVector dst_array, NumericVector src_array, List dimension_values);
RcppExport SEXP _jheem_core_do_array_overwrite(SEXP dst_arraySEXP, SEXP src_arraySEXP, SEXP dimension_valuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type dst_array(dst_arraySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type src_array(src_arraySEXP);
    Rcpp::traits::input_parameter< List >::type dimension_values(dimension_valuesSEXP);
    rcpp_result_gen = Rcpp::wrap(do_array_overwrite(dst_array, src_array, dimension_values));
    return rcpp_result_gen;
END_RCPP
}
// do_expand_array
RObject do_expand_array(NumericVector dst_array, NumericVector src_array);
RcppExport SEXP _jheem_core_do_expand_array(SEXP dst_arraySEXP, SEXP src_arraySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type dst_array(dst_arraySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type src_array(src_arraySEXP);
    rcpp_result_gen = Rcpp::wrap(do_expand_array(dst_array, src_array));
    return rcpp_result_gen;
END_RCPP
}
// do_get_expand_indices
RObject do_get_expand_indices(IntegerVector dst_array, List src_dim_names, int index_from);
RcppExport SEXP _jheem_core_do_get_expand_indices(SEXP dst_arraySEXP, SEXP src_dim_namesSEXP, SEXP index_fromSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type dst_array(dst_arraySEXP);
    Rcpp::traits::input_parameter< List >::type src_dim_names(src_dim_namesSEXP);
    Rcpp::traits::input_parameter< int >::type index_from(index_fromSEXP);
    rcpp_result_gen = Rcpp::wrap(do_get_expand_indices(dst_array, src_dim_names, index_from));
    return rcpp_result_gen;
END_RCPP
}
// do_access_overwrite
NumericVector do_access_overwrite(NumericVector dst, NumericVector src, IntegerVector dst_indices, IntegerVector src_indices);
RcppExport SEXP _jheem_core_do_access_overwrite(SEXP dstSEXP, SEXP srcSEXP, SEXP dst_indicesSEXP, SEXP src_indicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type dst(dstSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type src(srcSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dst_indices(dst_indicesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type src_indices(src_indicesSEXP);
    rcpp_result_gen = Rcpp::wrap(do_access_overwrite(dst, src, dst_indices, src_indices));
    return rcpp_result_gen;
END_RCPP
}
// do_access_add
NumericVector do_access_add(NumericVector dst, NumericVector src, IntegerVector dst_indices, IntegerVector src_indices);
RcppExport SEXP _jheem_core_do_access_add(SEXP dstSEXP, SEXP srcSEXP, SEXP dst_indicesSEXP, SEXP src_indicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type dst(dstSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type src(srcSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dst_indices(dst_indicesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type src_indices(src_indicesSEXP);
    rcpp_result_gen = Rcpp::wrap(do_access_add(dst, src, dst_indices, src_indices));
    return rcpp_result_gen;
END_RCPP
}
// do_access_subtract
NumericVector do_access_subtract(NumericVector dst, NumericVector src, IntegerVector dst_indices, IntegerVector src_indices);
RcppExport SEXP _jheem_core_do_access_subtract(SEXP dstSEXP, SEXP srcSEXP, SEXP dst_indicesSEXP, SEXP src_indicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type dst(dstSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type src(srcSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dst_indices(dst_indicesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type src_indices(src_indicesSEXP);
    rcpp_result_gen = Rcpp::wrap(do_access_subtract(dst, src, dst_indices, src_indices));
    return rcpp_result_gen;
END_RCPP
}
// do_access_multiply
NumericVector do_access_multiply(NumericVector dst, NumericVector src, IntegerVector dst_indices, IntegerVector src_indices);
RcppExport SEXP _jheem_core_do_access_multiply(SEXP dstSEXP, SEXP srcSEXP, SEXP dst_indicesSEXP, SEXP src_indicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type dst(dstSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type src(srcSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dst_indices(dst_indicesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type src_indices(src_indicesSEXP);
    rcpp_result_gen = Rcpp::wrap(do_access_multiply(dst, src, dst_indices, src_indices));
    return rcpp_result_gen;
END_RCPP
}
// do_access_divide
NumericVector do_access_divide(NumericVector dst, NumericVector src, IntegerVector dst_indices, IntegerVector src_indices);
RcppExport SEXP _jheem_core_do_access_divide(SEXP dstSEXP, SEXP srcSEXP, SEXP dst_indicesSEXP, SEXP src_indicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type dst(dstSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type src(srcSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dst_indices(dst_indicesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type src_indices(src_indicesSEXP);
    rcpp_result_gen = Rcpp::wrap(do_access_divide(dst, src, dst_indices, src_indices));
    return rcpp_result_gen;
END_RCPP
}
// apply_ontology_mapping
RObject apply_ontology_mapping(NumericVector src, NumericVector dst, CharacterVector from_values, CharacterVector to_values, bool na_rm);
RcppExport SEXP _jheem_core_apply_ontology_mapping(SEXP srcSEXP, SEXP dstSEXP, SEXP from_valuesSEXP, SEXP to_valuesSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type src(srcSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dst(dstSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type from_values(from_valuesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type to_values(to_valuesSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    rcpp_result_gen = Rcpp::wrap(apply_ontology_mapping(src, dst, from_values, to_values, na_rm));
    return rcpp_result_gen;
END_RCPP
}
// get_ontology_mapping_matrix
RObject get_ontology_mapping_matrix(List src_dim_names, List dst_dim_names, NumericVector dst, CharacterVector from_values, CharacterVector to_values);
RcppExport SEXP _jheem_core_get_ontology_mapping_matrix(SEXP src_dim_namesSEXP, SEXP dst_dim_namesSEXP, SEXP dstSEXP, SEXP from_valuesSEXP, SEXP to_valuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type src_dim_names(src_dim_namesSEXP);
    Rcpp::traits::input_parameter< List >::type dst_dim_names(dst_dim_namesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dst(dstSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type from_values(from_valuesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type to_values(to_valuesSEXP);
    rcpp_result_gen = Rcpp::wrap(get_ontology_mapping_matrix(src_dim_names, dst_dim_names, dst, from_values, to_values));
    return rcpp_result_gen;
END_RCPP
}
// get_ontology_mapping_indices
RObject get_ontology_mapping_indices(List src_dim_names, List dst_dim_names, CharacterVector from_values, CharacterVector to_values);
RcppExport SEXP _jheem_core_get_ontology_mapping_indices(SEXP src_dim_namesSEXP, SEXP dst_dim_namesSEXP, SEXP from_valuesSEXP, SEXP to_valuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type src_dim_names(src_dim_namesSEXP);
    Rcpp::traits::input_parameter< List >::type dst_dim_names(dst_dim_namesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type from_values(from_valuesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type to_values(to_valuesSEXP);
    rcpp_result_gen = Rcpp::wrap(get_ontology_mapping_indices(src_dim_names, dst_dim_names, from_values, to_values));
    return rcpp_result_gen;
END_RCPP
}
// do_get_reverse_indices_from_forward
IntegerVector do_get_reverse_indices_from_forward(List forward_indices, int n_from);
RcppExport SEXP _jheem_core_do_get_reverse_indices_from_forward(SEXP forward_indicesSEXP, SEXP n_fromSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type forward_indices(forward_indicesSEXP);
    Rcpp::traits::input_parameter< int >::type n_from(n_fromSEXP);
    rcpp_result_gen = Rcpp::wrap(do_get_reverse_indices_from_forward(forward_indices, n_from));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_jheem_core_overwrite_arr", (DL_FUNC) &_jheem_core_overwrite_arr, 4},
    {"_jheem_core_add_to_arr", (DL_FUNC) &_jheem_core_add_to_arr, 4},
    {"_jheem_core_overwrite_arr_with_scalar", (DL_FUNC) &_jheem_core_overwrite_arr_with_scalar, 2},
    {"_jheem_core_add_scalar_to_arr", (DL_FUNC) &_jheem_core_add_scalar_to_arr, 2},
    {"_jheem_core_do_array_overwrite", (DL_FUNC) &_jheem_core_do_array_overwrite, 3},
    {"_jheem_core_do_expand_array", (DL_FUNC) &_jheem_core_do_expand_array, 2},
    {"_jheem_core_do_get_expand_indices", (DL_FUNC) &_jheem_core_do_get_expand_indices, 3},
    {"_jheem_core_do_access_overwrite", (DL_FUNC) &_jheem_core_do_access_overwrite, 4},
    {"_jheem_core_do_access_add", (DL_FUNC) &_jheem_core_do_access_add, 4},
    {"_jheem_core_do_access_subtract", (DL_FUNC) &_jheem_core_do_access_subtract, 4},
    {"_jheem_core_do_access_multiply", (DL_FUNC) &_jheem_core_do_access_multiply, 4},
    {"_jheem_core_do_access_divide", (DL_FUNC) &_jheem_core_do_access_divide, 4},
    {"_jheem_core_apply_ontology_mapping", (DL_FUNC) &_jheem_core_apply_ontology_mapping, 5},
    {"_jheem_core_get_ontology_mapping_matrix", (DL_FUNC) &_jheem_core_get_ontology_mapping_matrix, 5},
    {"_jheem_core_get_ontology_mapping_indices", (DL_FUNC) &_jheem_core_get_ontology_mapping_indices, 4},
    {"_jheem_core_do_get_reverse_indices_from_forward", (DL_FUNC) &_jheem_core_do_get_reverse_indices_from_forward, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_jheem_core(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
