

#@Andrew - need to document
#'
#'@param weights An object of class 'jheem.likelihood.weights', generated by \code{\link{create.likelihood.weights}}
#'
#'@export
register.basic.likelihood.instructions <- function(outcome.for.data,
                                                   outcome.for.sim,
                                                   years,
                                                   stratifications=list(character(),
                                                                        'age','sex','risk','race',
                                                                        c('age','sex'), c('race','sex'), c('risk','sex'), c('risk','race')),
                                                   sources.to.use = NULL,
                                                   correlation.different.years,
                                                   correlation.different.stratifications,
                                                   correlation.different.sources,
                                                   correlation.same.source.different.details,
                                                   measurement.error.coefficient.of.variance,
                                                   weights)
{
    #@Andrew fill in arguments to constructor
    JHEEM.BASIC.LIKELIHOOD.INSTRUCTIONS$new()
    
}

JHEEM.BASIC.LIKELIHOOD.INSTRUCTIONS = R6::R6Class(
    'jheem.basic.likelihood.instructions',
    inherit = JHEEM.LIKELIHOOD.INSTRUCTIONS,
    
    public = list(
        
        initialize = function()
        {
            
        }
        
    )
)


JHEEM.BASIC.LIKELIHOOD = R6::R6Class(
    'jheem.basic.likelihood',
    inherit = JHEEM.LIKELIHOOD,
    portable = F,
    
    public = list(
        
        initialize = function(version,
                              location,
                              instructions,
                              error.prefix)
        {
            super$initialize(version = version,
                             location = location,
                             instructions = instructions,
                             error.prefix = error.prefix)
            
            # Need to check weights
            # - All dimension values in weights are present in the pulled data
            
        },
        
        compute = function(sim, log=T)
        {
            
        }
    ),
    
    private = list(
        
    )
)