#' @param outcome.for.sim A single character vector specifying the simulation outcome to use.
#' @param dimensions A character vector of dimensions, excluding year, from which stratifications will be generated.
#' @param levels.of.stratification A numeric vector specifying how the dimensions should be combined to form strata. '0' indicates totals (not stratified) while '1' indicates strata that are each stratified by one dimension at a time, '2' indicates strat that are each stratified by a combination of two dimensions at a time, etc. May not exceed the number of dimensions. Defaults to NULL, which is equivalent to '0'.
#' @param years A length two numeric vector specifying the baseline year (first) and the year which will be assessed against it (second).
#' @param probability.decreasing A single numeric value between 0 and 1 specifying probability that the outcome value is lower in the second year than in the first.
#' @param weights A list containing only numeric vectors and objects of class 'jheem.likelihood.weights', which are generated by \code{\link{create.likelihood.weights}}
#'
#' @export
create.bernoulli.likelihood.instructions <- function(outcome.for.sim,
                                                     dimensions = character(0),
                                                     levels.of.stratification = NULL,
                                                     years,
                                                     probability.decreasing,
                                                     weights) {
    JHEEM.BERNOULLI.LIKELIHOOD.INSTRUCTIONS$new(
        outcome.for.sim = outcome.for.sim,
        dimensions = dimensions,
        levels.of.stratification = levels.of.stratification,
        years,
        probability.decreasing = probability.decreasing,
        weights = weights
    )
}

JHEEM.BERNOULLI.LIKELIHOOD.INSTRUCTIONS <- R6::R6Class(
    "jheem.bernoulli.likelihood.instructions",
    inherit = JHEEM.LIKELIHOOD.INSTRUCTIONS,
    public = list(
        initialize = function(outcome.for.sim,
                              dimensions,
                              levels.of.stratification,
                              years,
                              probability.decreasing,
                              weights) {
            error.prefix <- paste0("Error creating basic likelihood instructions: ")

            # *probability.decreasing* is a single numeric value between 0 and 1
            if (!is.numeric(probability.decreasing) || is.null(probability.decreasing) || length(probability.decreasing) > 1 || is.na(probability.decreasing) || probability.decreasing > 1 || probability.decreasing < 0) {
                stop(paste0(error.prefix, "'probability.decreasing' must be a single numeric value between 0 and 1"))
            }
            private$i.probability.decreasing <- probability.decreasing

            # *years* is an integer vector of length two
            if (!is.numeric(years) || length(years) != 2 || any(is.na(years)) || is.null(years)) {
                stop(paste0(error.prefix, "'years' must be a length two non-NA, non-empty numeric vector"))
            }
            private$i.years <- as.integer(years)

            super$initialize(
                outcome.for.sim = outcome.for.sim,
                dimensions = dimensions,
                levels.of.stratification = levels.of.stratification,
                weights = weights,
                likelihood.class.generator = JHEEM.BERNOULLI.LIKELIHOOD
            )
        },
        equals = function(other) {
            if (!is(other, "jheem.likelihood.instructions")) {
                stop("'other' must be a 'jheem.likelihood.instructions' object")
            }
            if (!is.null(self$code) && !is.null(other$code)) {
                self$code == other$code
            } else {
                if (is(other, "jheem.bernoulli.likelihood.instructions")) {
                    to.compare.identical <- c(
                        "description",
                        "outcome.for.sim",
                        "years",
                        "probability.decreasing"
                    )
                    to.compare.setequal <- c("dimensions")

                    all(sapply(to.compare.identical, function(x) {
                        identical(self[[x]], other[[x]])
                    })) &&
                        all(sapply(to.compare.setequal, function(x) {
                            setequal(self[[x]], other[[x]])
                        })) &&
                        all(sapply(self$weights, function(x) {
                            any(sapply(other$weights, function(y) {
                                x$equals(y)
                            }))
                        })) &&
                        private$stratification.lists.equal(self$stratifications, other$stratifications)
                } else {
                    F
                }
            }
        }
    ),
    active = list(
        years = function(value) {
            if (missing(value)) {
                private$i.years
            } else {
                stop("Cannot modify a jheem.bernoulli.likelihood.instructions' 'years' - they are read-only")
            }
        },
        probability.decreasing = function(value) {
            if (missing(value)) {
                private$i.probability.decreasing
            } else {
                stop("Cannot modify a jheem.bernoulli.likelihood.instructions' 'probability.decreasing' - it is read-only")
            }
        }
    ),
    private = list(
        i.years = NULL,
        i.probability.decreasing = NULL,
        generate.weights.exponents = function(stratifications, weights, sim.ontology) {
            weights.exponents <- c()
            for (stratification in stratifications)
            {
                stop("Not yet implemented -- too hard to figure out which entry corresponds to which set of dimension values in weights")
            }
        }
    )
)

# class generator object
JHEEM.BERNOULLI.LIKELIHOOD <- R6::R6Class(
    "jheem.bernoulli.likelihood",
    inherit = JHEEM.LIKELIHOOD,
    portable = F,
    public = list(
        initialize = function(instructions,
                              version,
                              location,
                              data.manager,
                              throw.error.if.no.data,
                              error.prefix) {
            super$initialize(
                instructions = instructions,
                version = version,
                location = location,
                error.prefix = error.prefix
            )

            private$i.years <- instructions$years
            private$i.probability.decreasing <- instructions$probability.decreasing
        },
        check = function() {
            browser()
        }
    ),
    private = list(
        i.years = NULL,
        i.probability.decreasing = NULL,
        do.compute = function(sim, log = T, check.consistency = T, debug = F) {
            likelihoods.by.stratification <- sapply(private$i.stratifications, function(strat) {
                strat.keep.dimensions <- "year"
                if (strat != "") {
                    strat.keep.dimensions <- c(strat.keep.dimensions, strat)
                }
                sim.data <- sim$get(
                    outcome = private$i.outcome.for.sim,
                    keep.dimensions = strat.keep.dimensions,
                    dimension.values = list(year = private$i.years)
                )

                if (check.consistency) {
                    if (!is.null(dim(sim.data)) && names(dim(sim.data))[[1]] != "year") {
                        stop(paste0(error.prefix, "'year' was expected to be first dimension in simulation data but wasn't"))
                    }
                    if (!is.null(dim(sim.data)) && !identical(dimnames(sim.data)$year, sort(dimnames(sim.data)$year))) {
                        stop(paste0(error.prefix, "'year' dimension in simulation data was expected to be in sorted order but wasn't"))
                    }
                }

                # data will arrive with years sorted by value. *IF* year is the first dimension, this will work. Hopefully it is!
                differences <- diff(sim.data)

                if (private$i.years[[1]] < private$i.years[[2]]) {
                    decreasing <- differences < 0
                } else {
                    decreasing <- differences > 0
                }

                successes <- sum(decreasing)
                failures <- length(decreasing) - successes

                p <- private$i.probability.decreasing

                ifelse(log,
                    log(p) * successes + log(1 - p) * failures,
                    log(p)^successes * (1 - p)^failures
                )
            })

            # weights involve raising likelihoods to a power. Figuring out how to map weights to the correct likelihoods is difficult so not implementing at this time.
            # likelihoods.by.stratification = likelihoods.by.stratification ^ private$i.weights.exponents
            if (debug) browser()
            ifelse(log, sum(likelihoods.by.stratification), prod(likelihoods.by.stratification))
        }
    )
)
